
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Aug 16 19:44:45 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INCREMENT = 24;
  public static final int CHAR = 43;
  public static final int CONST = 40;
  public static final int ASTERISK = 25;
  public static final int SLASH = 28;
  public static final int NOT_EQUAL = 14;
  public static final int CONTINUE = 38;
  public static final int LPAREN = 17;
  public static final int GREATER = 26;
  public static final int LESS = 19;
  public static final int MINUS = 13;
  public static final int DECREMENT = 34;
  public static final int RPAREN = 4;
  public static final int SEMICOLON = 6;
  public static final int AND = 16;
  public static final int OR = 39;
  public static final int BOOL = 45;
  public static final int COMMA = 5;
  public static final int CLASS = 33;
  public static final int LESS_EQUAL = 30;
  public static final int PLUS = 3;
  public static final int ASSIGN = 42;
  public static final int IF = 10;
  public static final int IS_EQUAL = 21;
  public static final int DOT = 11;
  public static final int FINDANY = 47;
  public static final int EOF = 0;
  public static final int RETURN = 37;
  public static final int EQUAL = 18;
  public static final int GREATER_EQUAL = 29;
  public static final int NEW = 8;
  public static final int error = 1;
  public static final int PERCENT = 41;
  public static final int LCURLY = 12;
  public static final int NUMBER = 44;
  public static final int IDENT = 46;
  public static final int BREAK = 22;
  public static final int VOID = 15;
  public static final int RCURLY = 32;
  public static final int FOREACH = 49;
  public static final int COLON = 2;
  public static final int ELSE = 9;
  public static final int LSQUARE = 20;
  public static final int READ = 23;
  public static final int RSQUARE = 36;
  public static final int WHILE = 27;
  public static final int PROG = 35;
  public static final int EXTENDS = 7;
  public static final int PRINT = 31;
  public static final int FINDANDREPLACE = 48;
}

